// File generated by FlutterFire CLI.
//
// This is a placeholder so the app foundation compiles. Replace it with the
// real configuration produced by running:
//
//     flutterfire configure --project=<your-firebase-project>
//
// Do not commit production API keys here unless you have intentionally
// scoped your Firebase project to public client credentials only.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _placeholder('web');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _placeholder('android');
      case TargetPlatform.iOS:
        return _placeholder('ios');
      case TargetPlatform.macOS:
        return _placeholder('macos');
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'MaintenanceOS is not configured for ${defaultTargetPlatform.name}.',
        );
    }
  }

  static FirebaseOptions _placeholder(String platform) {
    return FirebaseOptions(
      apiKey: 'REPLACE_ME_${platform.toUpperCase()}',
      appId: 'REPLACE_ME_APP_ID',
      messagingSenderId: 'REPLACE_ME_SENDER_ID',
      projectId: 'maintenanceos-dev',
      storageBucket: 'maintenanceos-dev.appspot.com',
    );
  }
}
